Repository DO-SOPT-CDS-APP-2/CDS-APP-2-ANDROID, pull requests merged in 2023-11, with the labels that each got.

#7 [FEAT#5] NaviagtionBar 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/cds29cm/presentation/MainActivity.kt
  app/src/main/java/org/sopt/cds29cm/presentation/MockActivity.kt
  app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryFragment.kt
  app/src/main/java/org/sopt/cds29cm/presentation/home/HomeFragment.kt
  app/src/main/res/drawable/bnv_category_ic.xml
  app/src/main/res/drawable/bnv_home_ic.xml
  app/src/main/res/drawable/bnv_like_ic.xml
  app/src/main/res/drawable/bnv_my_ic.xml
  app/src/main/res/drawable/bnv_search_ic.xml
  app/src/main/res/drawable/ic_category_off.xml
  app/src/main/res/drawable/ic_category_on.xml
  app/src/main/res/drawable/ic_home_off.xml
  app/src/main/res/drawable/ic_home_on.xml
  app/src/main/res/drawable/ic_like_off.xml
  app/src/main/res/drawable/ic_like_on.xml
  app/src/main/res/drawable/ic_my_off.xml
  app/src/main/res/drawable/ic_my_on.xml
  app/src/main/res/drawable/ic_search_off.xml
  app/src/main/res/drawable/ic_search_on.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_mock.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/menu/menu_home.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ⭐ [FEAT]

#12 [HOTFIX/#11] FontWeight 수정
  app/src/main/res/font/font_gmarket_sans_bold.xml
  app/src/main/res/font/font_gmarket_sans_light.xml
  app/src/main/res/font/font_gmarket_sans_medium.xml
  app/src/main/res/font/font_noto_sans_kr_bold.xml
  app/src/main/res/font/font_noto_sans_kr_medium.xml
  app/src/main/res/font/font_noto_sans_kr_regular.xml
  app/src/main/res/font/font_noto_sans_kr_semibold.xml
  app/src/main/res/values/appearances.xml
Labels: 🚑️ [HOTFIX], 상호

#13 [UI/#6,#9] CategoryFragment 뷰 / UI 구현
  app/src/main/java/org/sopt/cds29cm/data/CategoryHorizontal.kt
  app/src/main/java/org/sopt/cds29cm/data/CategoryVertical.kt
  app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryFragment.kt
  app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryHorizontalAdapter.kt
  app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryHorizontalViewHolder.kt
  app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryVerticalLeftAdapter.kt
  app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryVerticalLeftViewHolder.kt
  app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryVerticalRightAdapter.kt
  app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryVerticalRightViewHolder.kt
  app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryViewModel.kt
  app/src/main/res/drawable/ic_alert_black.xml
  app/src/main/res/drawable/ic_cart_black.xml
  app/src/main/res/drawable/ic_category_vertical_recyclerview_banner.png
  app/src/main/res/drawable/ic_detail_right_gray.xml
  app/src/main/res/drawable/ic_search_black.xml
  app/src/main/res/drawable/img_category_20.png
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/item_category_horizontal.xml
  app/src/main/res/layout/item_category_vertical_left.xml
  app/src/main/res/layout/item_category_vertical_right.xml
Labels: 💟 [UI], 민영

#17 [UI/#14] HatCategory 뷰/ UI 구현
  app/src/main/java/org/sopt/cds29cm/data/BestItem.kt
  app/src/main/java/org/sopt/cds29cm/data/CategoryFilter.kt
  app/src/main/java/org/sopt/cds29cm/data/RequestCategoryItemDTO.kt
  app/src/main/java/org/sopt/cds29cm/data/RequestHeartDTO.kt
  app/src/main/java/org/sopt/cds29cm/data/ResponseCategoryItemDTO.kt
  app/src/main/java/org/sopt/cds29cm/data/ResponseHeartDTO.kt
  app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryHorizontalAdapter.kt
  app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryVerticalLeftAdapter.kt
  app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryVerticalRightAdapter.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatCategory/HatCategoryBestItemAdapter.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatCategory/HatCategoryBestItemViewHolder.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatCategory/HatCategoryFilterAdapter.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatCategory/HatCategoryFilterViewHolder.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatCategory/HatCategoryFragment.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatCategory/HatCategoryHorizontalCategoryAdapter.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatCategory/HatCategoryHorizontalCategoryViewHolder.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatCategory/HatCategoryItemAdapter.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatCategory/HatCategoryItemViewHolder.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatCategory/HatCategoryViewModel.kt
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_detail_down_black_10dp.xml
  app/src/main/res/drawable/ic_detail_down_gray_10dp.xml
  app/src/main/res/drawable/ic_detail_right_gray_10dp.xml
  app/src/main/res/drawable/ic_heart.xml
  app/src/main/res/drawable/ic_star_gray.xml
  app/src/main/res/drawable/img_category_15.xml
  app/src/main/res/drawable/img_category_16.xml
  app/src/main/res/drawable/img_category_29.png
  app/src/main/res/drawable/img_hat_category_30.png
  app/src/main/res/drawable/img_hat_category_31.png
  app/src/main/res/drawable/img_hat_category_32.png
  app/src/main/res/drawable/img_hat_category_33.png
  app/src/main/res/drawable/img_hatcategory_13.png
  app/src/main/res/drawable/shape_gray_line_15_rect.xml
  app/src/main/res/layout/fragment_hat_category.xml
  app/src/main/res/layout/item_hat_category_best_hat.xml
  app/src/main/res/layout/item_hat_category_filter.xml
  app/src/main/res/layout/item_hat_category_horizontal_category.xml
  app/src/main/res/layout/item_hat_category_vertical.xml
Labels: 💟 [UI], 민영
