Repository DO-SOPT-CDS-APP-2/CDS-APP-2-ANDROID, pull requests merged in 2023-12, with the labels that each got.

#21 [FEAT/#16] HomeFragment / 서버통신
  app/src/main/java/org/sopt/cds29cm/data/dataclass/HomeNotia.kt
  app/src/main/java/org/sopt/cds29cm/data/dto/request/HeartRequestDto.kt
  app/src/main/java/org/sopt/cds29cm/data/dto/response/HeartResponseDto.kt
  app/src/main/java/org/sopt/cds29cm/data/dto/response/HomeResponseDto.kt
  app/src/main/java/org/sopt/cds29cm/data/mock/HomeIssueViewModel.kt
  app/src/main/java/org/sopt/cds29cm/data/mock/HomeMarronViewModel.kt
  app/src/main/java/org/sopt/cds29cm/data/mock/HomeNotiaViewModel.kt
  app/src/main/java/org/sopt/cds29cm/data/mock/HomePopularViewModel.kt
  app/src/main/java/org/sopt/cds29cm/data/mock/HomeRecommendViewModel.kt
  app/src/main/java/org/sopt/cds29cm/data/service/HomeService.kt
  app/src/main/java/org/sopt/cds29cm/module/ServicePool.kt
  app/src/main/java/org/sopt/cds29cm/presentation/home/HomeFragment.kt
  app/src/main/java/org/sopt/cds29cm/presentation/home/HomeIssueAdapter.kt
  app/src/main/java/org/sopt/cds29cm/presentation/home/HomeIssueViewHolder.kt
  app/src/main/java/org/sopt/cds29cm/presentation/home/HomeMarronViewHolder.kt
  app/src/main/java/org/sopt/cds29cm/presentation/home/HomeNotiaAdapter.kt
  app/src/main/java/org/sopt/cds29cm/presentation/home/HomeNotiaViewHolder.kt
  app/src/main/java/org/sopt/cds29cm/presentation/home/HomeRecommendViewHolder.kt
  app/src/main/java/org/sopt/cds29cm/presentation/home/HomeViewModel.kt
  app/src/main/java/org/sopt/cds29cm/presentation/home/HomeViewModelFactory.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_marron.xml
  app/src/main/res/layout/item_home_notia.xml
  app/src/main/res/layout/item_home_popular.xml
  app/src/main/res/layout/item_home_recommend.xml
Labels: ⭐ [FEAT], 💫유빈

#20 [FEAT/#3, #18] HatDetail 뷰 UI & 서버통신 구현
  README.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/cds29cm/data/dataclass/HatDetailBrand.kt
  app/src/main/java/org/sopt/cds29cm/data/dataclass/HatDetailEvent.kt
  app/src/main/java/org/sopt/cds29cm/data/dto/response/HatDetailResponseDto.kt
  app/src/main/java/org/sopt/cds29cm/data/mock/mockHatDetailBrandList.kt
  app/src/main/java/org/sopt/cds29cm/data/mock/mockHatDetailEventList.kt
  app/src/main/java/org/sopt/cds29cm/data/service/HatDetailService.kt
  app/src/main/java/org/sopt/cds29cm/module/ItemService.kt
  app/src/main/java/org/sopt/cds29cm/module/ServicePool.kt
  app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryFragment.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatCategory/HatCategoryFragment.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatCategory/HatCategoryItemAdapter.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatDetail/HatDetailActivity.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatDetail/HatDetailBrandAdapter.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatDetail/HatDetailBrandViewHolder.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatDetail/HatDetailEventAdapter.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatDetail/HatDetailEventViewHolder.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatDetail/HatDetailViewModel.kt
  app/src/main/java/org/sopt/cds29cm/util/UiState.kt
  app/src/main/res/drawable/ic_29cm.png
  app/src/main/res/drawable/ic_btn_up.xml
  app/src/main/res/drawable/ic_cart_black.xml
  app/src/main/res/drawable/ic_detail_down_black_24dp.xml
  app/src/main/res/drawable/ic_detail_down_gray_24dp.xml
  app/src/main/res/drawable/ic_detail_right_gray_10dp.xml
  app/src/main/res/drawable/ic_five_stars_black.xml
  app/src/main/res/drawable/ic_home_black.xml
  app/src/main/res/drawable/ic_like.xml
  app/src/main/res/drawable/ic_like_off_gray_24dp.xml
  app/src/main/res/drawable/ic_like_off_gray_44dp.xml
  app/src/main/res/drawable/ic_question_circle.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/drawable/img_hat_detail_3.xml
  app/src/main/res/drawable/img_hat_detail_4.xml
  app/src/main/res/drawable/img_hat_detail_review.xml
  app/src/main/res/drawable/img_hat_detail_review_6.png
  app/src/main/res/drawable/img_hat_size.xml
  app/src/main/res/drawable/img_hatdetail_19.png
  app/src/main/res/drawable/img_hatdetail_21.png
  app/src/main/res/drawable/img_hatdetail_22.png
  app/src/main/res/drawable/img_hatdetail_23.png
  app/src/main/res/drawable/img_hatdetail_24.png
  app/src/main/res/drawable/img_hatdetail_25.png
  app/src/main/res/drawable/img_hatdetail_26.png
  app/src/main/res/drawable/img_hatdetail_27.png
  app/src/main/res/drawable/img_hatdetail_28.png
  app/src/main/res/drawable/shape_bg_fill_border_line_05_rect.xml
  app/src/main/res/drawable/shape_black_line_1_rect.xml
  app/src/main/res/drawable/shape_border_line_05_rect.xml
  app/src/main/res/drawable/shape_border_line_1_rect.xml
  app/src/main/res/layout/activity_hat_detail.xml
  app/src/main/res/layout/item_recommend_brand.xml
  app/src/main/res/layout/item_recommend_event.xml
  app/src/main/res/values/appearances.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ⭐ [FEAT], 상호

#26 [FIX/#25] 유빈 민영 채점 결과 발표
  app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryFragment.kt
  app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryHorizontalAdapter.kt
  app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryVerticalLeftAdapter.kt
  app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryVerticalLeftViewHolder.kt
  app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryVerticalRightAdapter.kt
  app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryVerticalRightViewHolder.kt
  app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryViewModel.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatCategory/HatCategoryFragment.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatCategory/HatCategoryItemAdapter.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatCategory/HatCategoryItemViewHolder.kt
  app/src/main/java/org/sopt/cds29cm/presentation/hatCategory/HatCategoryViewModel.kt
  app/src/main/java/org/sopt/cds29cm/presentation/home/HomeFragment.kt
  app/src/main/java/org/sopt/cds29cm/presentation/home/HomeViewModel.kt
  app/src/main/res/drawable/img_home_66.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_hat_category.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_hat_category_vertical.xml
  app/src/main/res/layout/item_home_marron.xml
  app/src/main/res/layout/item_home_notia.xml
  app/src/main/res/values/appearances.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: 🔨 [FIX], 상호
